self.detection_patterns = [
    r"ignore (?:all|previous|your) instructions",
    r"disregard (?:all|previous|your) instructions",
    r"bypass (?:all|previous|your|these) (?:instructions|rules)",
    r"forget (?:all|previous|your) instructions",
    r"system prompt",
    r"don'?t follow (?:your|the) instructions",
    r"new instructions:?",
    r"as an AI",
    r"your rules",
    r"pretend to be",
    r"act as if",
    r"ignore your programming",
    r"role[ -]?play",
    r"please jailbreak",
    r"unfiltered response",
    r"reset your instructions",
    r"disregard above",
    r"output only",
    r"print only",
    r"write code that",
    r"how to hack",
    r"remove all restrictions",
    r"no ethical guidelines",
    r"no limitations",
    r"simulate",
    r"break character",
    r"act as system",
    r"developer mode",
]


